# Generated by Django 3.2.6 on 2021-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_auto_20210929_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_arrival_at_port_of_dis_year',
            field=models.IntegerField(blank=True, help_text='Date in format: YYYY', null=True, verbose_name='Year of arrival at port of disembarkation (YEARAM)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_departed_africa_year',
            field=models.IntegerField(blank=True, help_text='Date in format: YYYY', null=True, verbose_name='Year departed Africa'),
        ),
    ]
