# Generated by Django 3.2.6 on 2021-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='voyage_sources',
        ),
    ]
