# Generated by Django 3.2.6 on 2021-09-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_auto_20210917_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesourcesconnection',
            name='source_order',
        ),
    ]
