# Generated by Django 3.2.6 on 2021-09-29 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_remove_voyagesourcesconnection_source_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagedates',
            name='imp_arrival_at_port_of_dis_year',
            field=models.IntegerField(blank=True, help_text='Date in format: YYYY', max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(\\d{1,2}|),(\\d{1,2}|),(\\d{4}|)$'), code='invalid', message='Please type a date in the format MM,DD,YYYY (individual entries may be blank)')], verbose_name='Year of arrival at port of disembarkation (YEARAM)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='imp_departed_africa_year',
            field=models.IntegerField(blank=True, help_text='Date in format: YYYY', max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(\\d{1,2}|),(\\d{1,2}|),(\\d{4}|)$'), code='invalid', message='Please type a date in the format MM,DD,YYYY (individual entries may be blank)')], verbose_name='Year departed Africa'),
        ),
        migrations.AlterField(
            model_name='voyageoutcome',
            name='voyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_outcomes', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='voyageship',
            name='tonnage_mod',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Tonnage standardized on British measured tons 1773-1870'),
        ),
    ]
